services:
  plin-bot:
    container_name: plin_bot
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - TZ=America/Maceio  # <-- Adicione isto!
    env_file:
      - .env